/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ShortcutsRouteImport } from './routes/shortcuts';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CConversationIdRouteImport } from './routes/c.$conversationId';

const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const CConversationIdRoute = CConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/shortcuts': typeof ShortcutsRoute;
  '/c/$conversationId': typeof CConversationIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/shortcuts': typeof ShortcutsRoute;
  '/c/$conversationId': typeof CConversationIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/shortcuts': typeof ShortcutsRoute;
  '/c/$conversationId': typeof CConversationIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/settings' | '/shortcuts' | '/c/$conversationId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/settings' | '/shortcuts' | '/c/$conversationId';
  id: '__root__' | '/' | '/settings' | '/shortcuts' | '/c/$conversationId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  ShortcutsRoute: typeof ShortcutsRoute;
  CConversationIdRoute: typeof CConversationIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortcuts': {
      id: '/shortcuts';
      path: '/shortcuts';
      fullPath: '/shortcuts';
      preLoaderRoute: typeof ShortcutsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/c/$conversationId': {
      id: '/c/$conversationId';
      path: '/c/$conversationId';
      fullPath: '/c/$conversationId';
      preLoaderRoute: typeof CConversationIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ShortcutsRoute: ShortcutsRoute,
  CConversationIdRoute: CConversationIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
